### ISSUE TITLE
Dependency regex does not recognize dependencies without version constraint

### ISSUE THREAD

**Issue by J-Vaughan** [J-Vaughan/bpm#1]
## Current regex

```regexp
/\s*(.+),\s(.*)/
```

### Matches

```text
json,       >= 2.3
readline,   == 0.4.2
jquyery,    <= 12.2.0 && > 13.0
rubycopy,   ~> 1.2.2
```

### Does not match

```text
noconstraint
anyversion
```

**Comment by blazingkin** [comment]
You can make it match both cases by switching to

`/\s*(.+)(,\s(.*))?/`

That will match most things though since `/\s*(.+)/` matches every non-empty line. I'm not quite sure what the use case is.
 
It also changes your capturing group to include the comma and whitespace, those can be trimmed off

You may want to try parsing without regex too, I've found that regex often complicates things

**Comment by J-Vaughan** [comment]
With TOML, this _specific_ issue no longer exists. Thanks for your help.
